version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

jobs:
  lint:
    docker:
      - image: circleci/python:3.9-buster
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo pip install --upgrade pip
            sudo pip install -r requirements.txt
            sudo pip install pylint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint
            python3 -m venv venv
            . venv/bin/activate
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Lint files
          command: |
            . venv/bin/activate
            make lint
  
  build-image:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run:
          name: Build Image
          command: |
            docker build -t hello-wolrd .
            docker tag hello-world vasudevla/hello-world
            docker login
            docker push vasudevla/hello-world

workflows:
  build_and_deploy:
    jobs:
      - lint
      - build-image:
          requires: [lint]